version: '3.7'
services:
  backend:
    build: ./backend
    environment:
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-http://localhost:3000}
    restart: always
    ports:
      - ${BACKEND_PORT:-8080}:8080
    networks:
      - project-dev


  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT:-http://localhost:8080}
    ports:
      - ${BACKEND_PORT:-3000}:3000
    networks:
      - project-dev

networks:
  project-dev:
    driver: bridge
